### ISSUE TITLE
Arithmetic on pointer passed by variable should not affect data

### ISSUE THREAD

**Issue by SignumTemporis** [tebe6502/Mad-Pascal#100]
## Issue description

Arithmetic on a pointer passed by variable modifies the data it refers to while it should effect the pointer itself.

For FPC -MDelphi v3.2.2 it works as expected.

Mad-Pascal Compiler version 9cc0813
Mad-Assembler version 40bfd80

## Code to reproduce the issue
```Pascal
uses crt;

type BytePtr = ^Byte;

var
  data: array [0 .. 1] of Byte;
  p: BytePtr;

procedure DoSomething(var p2: Pointer);
begin
  p2 := p2 + 1;
end;

begin
  data[0] := 10;  data[1] := 20;

  p := @data;
  Write(p^);
  DoSomething(p);
  WriteLn(' ', p^);

  ReadKey();
end.
```

### Expected
```
10 20
```

### Actual
```
10 11
```

**Comment by tebe6502** [comment]
fixed, https://github.com/tebe6502/Mad-Pascal/blob/master/samples/tests/tests-pointer/arithmetic_var.pas

**Comment by SignumTemporis** [comment]
Works for me now.
