### ISSUE TITLE
Unable to reuse the MPT player with another music file.

### ISSUE THREAD

**Issue by delysio** [tebe6502/Mad-Pascal#104]
Unable to reuse the MPT player with another music file. The msx.init procedure does not play a new module from the beginning.

How to reproduce:

[main.pas](https://pastebin.com/aRVQ9Nd8)
[resources.rc](https://pastebin.com/rK5ENrvT)

**Comment by tebe6502** [comment]
issue #104 fixed, https://github.com/tebe6502/Mad-Pascal/tree/master/base/atari/players
