### ISSUE TITLE
The compiller requires write access to library files for compilation (?)

### ISSUE THREAD

**Issue by t-w** [tebe6502/Mad-Pascal#117]
I have built the compiler (1.6.6) on Linux (using FreePascal) and manually installed it system-wide (somewhere in `/opt/...`). Initially it was working - but then I changed file permissions so that a regular user cannot access the compiler/library files for _writing_ (precisely - I changed the file ownership from a regular user to root/admin - as it should be on a regular multiuser system) - and the compilations started failing, with rather strange errors, from:
```
/opt/retro/madpascal/lib/crt.pas (1,10) Error: Syntax error, '.' expected but 'unknown token' found
```
or
```
/opt/retro/madpascal/lib/types.pas (446,5) Error: Syntax error, '.' expected but 'END' found
```
to errors with "Access violation" (like the one in #112).

Using `strace` revealed (it doesn't matter if it is for C64 or Atari):
```
$ strace -o /tmp/output2 mp -t c64 a_test0.pas -ipath:/opt/retro/madpascal/lib

[...]

$ less /tmp/output2
[...]
access("/opt/retro/madpascal/lib/crt.pas", F_OK) = 0
stat("/opt/retro/madpascal/lib/crt.pas", {st_mode=S_IFREG|0644, st_size=3929, ...}) = 0
access("/opt/retro/madpascal/lib/crt.pas", F_OK) = 0
stat("/opt/retro/madpascal/lib/crt.pas", {st_mode=S_IFREG|0644, st_size=3929, ...}) = 0
access("/opt/retro/madpascal/lib/crt.pas", F_OK) = 0
stat("/opt/retro/madpascal/lib/crt.pas", {st_mode=S_IFREG|0644, st_size=3929, ...}) = 0
open("/opt/retro/madpascal/lib/crt.pas", O_RDWR|O_LARGEFILE) = -1 EACCES (Permission denied)
```
so the compiler indeed tries to open a library source (unit) for _writing_ during compilation, and the compilation fails if it cannot...

A rather strange, not very safe behaviour, it would be good if it was corrected.

**Comment by tebe6502** [comment]
Compiler does not require write access to library files to compile

try 1.6.8

**Comment by t-w** [comment]
Yes, it still does. Fix above.
