### ISSUE TITLE
Very slow compile time with StrToInt?

### ISSUE THREAD

**Issue by aydindemircioglu** [tebe6502/Mad-Pascal#125]
I am not sure why, but this small example needs 5 seconds to compile when I use StrToInt.
When I comment out the StrToInt, it is only 0.7 seconds.
The more 'readValues' I add, the longer the compile time.
(In my project it takes over 171 seconds to compile, without this single line its 3 seconds).

Any reason why?

program minexample;

{$librarypath '../../tools/Mad-Pascal/blibs/'}
{$librarypath '../../tools/Mad-Pascal/base/'}
{$librarypath '../../tools/Mad-Pascal/lib/'}

uses sysutils, b_crt; // b_utils;

function readValue(minValue:integer; maxValue:integer): integer;
var
  ivalue: integer;
  x, y: byte;
begin;
  x := CRT_WhereX;
  y := CRT_WhereY;
  repeat
    CRT_GotoXY (x, y);
    CRT_Write('      '~);
    CRT_GotoXY (x, y);
    ivalue := StrToInt(CRT_ReadString(5));
  until (minValue <= ivalue) and (ivalue <= maxValue);
  result := ivalue;
end;

begin;
  readValue(0, 1000);
  readValue(0, 1000);
  readValue(0, 1000);
  readValue(0, 1000);
  readValue(0, 1000);
  readValue(0, 1000);
  readValue(0, 1000);
end.

**Comment by aydindemircioglu** [comment]
i now realize its not the StrToInt, but the CRT_ReadString. it becomes even worse when one drops the limit, so one uses CRT_ReadString(); only.
using the functions directly doesnt seem to create the overhead
```
    k := CRT_ReadStringI(5);
    k := Antic2Atascii(k);
    ivalue := StrToInt(k);
```
compiles in 0.92s vs 8.29s when 13 calls are performed.

**Comment by tebe6502** [comment]
curious

i suggest readln(ivalue)

**Comment by tebe6502** [comment]
issue #125 fixed
