### ISSUE TITLE
Commander X16 target support

### ISSUE THREAD

**Issue by MADRAFi** [tebe6502/Mad-Pascal#131]
https://github.com/Squall-FF8/Publicly-Shared/tree/main/X16/Pascal/lib

https://github.com/X16Community/x16-docs/blob/master/X16%20Reference%20-%2008%20-%20Memory%20Map.md

https://github.com/jimmydansbo/vtuilib

**Comment by zbyti** [comment]
nice to have: https://en.wikipedia.org/wiki/WDC_65C02#New_and_modified_instructions for Neo6502 and X16

**Comment by zbyti** [comment]
@tebe6502 open your mind to the new 65c02 processor because it is the most common choice now: you will get X16, Lynx and Neo6502.

Enough code for Atari ;)

**Comment by zbyti** [comment]
done
