### ISSUE TITLE
1.6.8 still marked as "Latest" stable release instead of 1.6.9 ... is this intentional?

### ISSUE THREAD

**Issue by elisimpson** [tebe6502/Mad-Pascal#132]
Just wondering why 1.6.9 isn't marked as the latest stable release. If this is intentional please ignore.

**Comment by zbyti** [comment]
yes, releases could appear more often because informally the main branch is considered the most stable.

@tebe6502 please consider the new release of Mad Pascal :]

**Comment by tebe6502** [comment]
GitHub used to automatically mark 'latest', now you have to manually
