### ISSUE TITLE
The sysutils unit cannot be compiled for target raw.

### ISSUE THREAD

**Issue by at91rm9200** [tebe6502/Mad-Pascal#147]
Hello,

the compiler complaints about missing identifiers, if one includes the unit sysutils for the target "raw".
The attached patch fixes the problem for me.

[patch_sysutils_raw.txt](https://github.com/tebe6502/Mad-Pascal/files/14923893/patch_sysutils_raw.txt)

Regards, Bernd.

**Comment by tebe6502** [comment]
Now sysutils has been separated by platform, this solves the problem for the RAW target

**Comment by at91rm9200** [comment]
Thank you.
