### ISSUE TITLE
Bug: Wrong optimization

### ISSUE THREAD

**Issue by zbyti** [tebe6502/Mad-Pascal#18]
```delphi
var
  joy      : byte absolute $ff08;
  pio      : byte absolute $fd30;

begin
  repeat
    pio := $ff;
    joy := 2;
    if (joy xor $ff) = 1 then writeln('UP');
  until false;
end.
```
```
; --- RepeatUntilProlog
l_005B

; optimize OK (test.pas), line = 7

	lda #$FF
	sta PIO

; optimize OK (test.pas), line = 8

	lda #$02
	sta JOY

; optimize OK (test.pas), line = 10

	eor #$FF
	cmp #$01
	jne l_0079
	@printSTRING #CODEORIGIN+$0000
	@printEOL
l_0079

; optimize OK (test.pas), line = 11

	jmp l_005B
```

**Comment by zbyti** [comment]
może jeżeli zmienna jest rejestrem R/W to może warto dać jakąś dyrektywę aby nie optymalizowało wystąpienia takiej zmiennej?

w powyższym do JOY najpierw musimy zapisać by wskazać o który port joysticka nam chodzi po czym dopiero możemy odczytać jego stan.

**Comment by zbyti** [comment]
https://wiki.freepascal.org/FPC_New_Features_Trunk#Support_for_.22volatile.22_intrinsic

**Comment by zbyti** [comment]
Same case **test_consecutive_reading_of_changing_register_fails**  https://github.com/tebe6502/Mad-Pascal/blob/master/test/tests/test_fails.py

**Comment by tebe6502** [comment]
[volatile] added, problem solved
