### ISSUE TITLE
Issue with loading resources

### ISSUE THREAD

**Issue by GSoftwareDevelopment** [tebe6502/Mad-Pascal#33]
Setting the loading of resources that are close to each other (within the page) causes their mutual (probably) deletion.

e.g.
~~~
res1 = $b500;
res2 = $b520;
res3 = $b5f0;

res1 rcasm 'res1.asm'
res2 rcasm 'res2.asm'
res3 rcasm 'res3.asm'
~~~

Resource sizes tiny (several bytes). The compilation goes without any problems, but running it gives an error.

I have to manipulate the loading order, between other resources located in other memory areas, e.g.
-First I load 'res1',
- then 'image'
- and then 'res2'.

**Comment by GSoftwareDevelopment** [comment]
At the moment, I don't know if it's a BUG, because if the resources are loaded in the order they appear in memory, the error doesn't occur. However, this is not mentioned anywhere, which can be annoying for a novice MadPascal user.

**Comment by zbyti** [comment]
Resource sorting is under development, @tebe6502  has this in mind.

**Comment by GSoftwareDevelopment** [comment]
Roger, closing topic
