### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by GSoftwareDevelopment** [tebe6502/Mad-Pascal#36]
From time to time I get a message during compilation:
~~~
start.a65 (126) WARNING: Infinite loop by label VADR
.
.
.
17107 lines of source assembled in 20 pass (infinite loop)
~~~

start.a65 warning code:
~~~asm6502
; ------------------------------------------------------------

START
	tsx
	stx MAIN.@halt+1

	.ifdef fmulinit
	fmulinit
	eif

VLEN	= VARDATASIZE-VARINITSIZE
VADR	= DATAORIGIN+VARINITSIZE <-- Here he points out the warning.

	ift VADR > $BFFF
	ert 'Invalid memory address range ',VADR
	eli (VLEN>0) && (VLEN<=256)
	ldx #256-VLEN
	lda #0
	sta:rne VADR+VLEN-256,x+
	eli VLEN>0
	@fill #VADR #VLEN #0
	eif
~~~
Trying to run a program compiled this way, ends up with the emulator "crashing" during program initialization.

Sometimes simply adding or removing code helps.
That being said, I would venture to suggest that this may be due to a paging error - a tight page boundary - or something similar.

A bit of an annoying bug, because it forces you to combine things.

**Comment by GSoftwareDevelopment** [comment]
I'm using version 1.6.4, and the error is showing. I'm sending link to package with program, where during compilation error is showing (Sorry for a big app :P)
https://drive.google.com/file/d/1-sdKFljstbYx456_RghTg-FNjYMBYutw/view?usp=sharing

**Comment by GSoftwareDevelopment** [comment]
Unfortunately, the "infinite loop" error also shows up in the new version.

I already thought it was gone, until here it suddenly showed up. And again, adding/including some (arbitrary, not required) instruction, causes that, the error disappears.

You can "cut yourself" and look for a bug that is not really in the code.

**Comment by GSoftwareDevelopment** [comment]
Unfortunately, the "infinite loop" error also shows up in the new version.

I already thought it was gone, until here it suddenly showed up. And again, adding/including some (arbitrary, not required) instruction, causes that, the error disappears.

You can "cut yourself" and look for a bug that is not really in the code.

**Comment by tebe6502** [comment]
use the constant DATAORIGIN

-data:address
