### ISSUE TITLE
PASCAL procedure/function modifier

### ISSUE THREAD

**Issue by GSoftwareDevelopment** [tebe6502/Mad-Pascal#37]
I have a suggestion for the modifier name, to change it to "RELEASELOCAL" or "FREELOCALVAR" or something that clearly associates with the modifier's function of allocating/releasing memory for local variables.

**Comment by zbyti** [comment]
Use globals variables with absolute mapping. Feature of reuse memory is compilator thing and probably new feature request.

**Comment by GSoftwareDevelopment** [comment]
I think you misunderstood my message.

I suggest you rename the PASCAL modifier (for functions/procedures) to something more appropriate for the action it performs.

Alternatively, the other way around, i.e.
Use a modifier, e.g. KEEPVARS, to keep local variables in memory at all times.

The normal Pascal behavior was to release local variables from memory and create them anew each time a function/procedure was called.

So, the above modifier is perfectly fine in place of the completely incompatible "PASCAL" - as if it's a feature of the language, and we know it's not, as it's normal behavior for any language that supports calling context.

Translated with www.DeepL.com/Translator (free version)

**Comment by zbyti** [comment]
Myślę, że to jest do zamknięcia - proponowana realizacja jest trochę bez sensu.

Albo kompilator sam będzie umiał rozpoznać, które zmienne lokalne można użyć ponownie albo nie.

Jeżeli sam mam wskazywać takie zmienne to równie dobrze sam mogę dbać o ponowne używanie pewnej puli zmiennych globalnych.

Tak robiłem w ostatnim projekcie i się w tym pogubiłem do póki nie zacząłem emulować aliasów do tych zmiennych. Zrobiło się z tego więcej pisaniny a na końcu i tak straciłem kontrolę czy jak procedura nie wywołuje procedury to czy moja pula nie jest za mała i jednak nie nadpiszę swoich danych.

Wyszło na to, że kompromisem dla ponownego używania zmiennych jest podziale projektu na moduły itd.

---

@tebe6502 uważam, że nie ma sensu by to dalej wisiało i jest do zamknięcia.
