### ISSUE TITLE
MACRO procedure/function modifier suggestion

### ISSUE THREAD

**Issue by GSoftwareDevelopment** [tebe6502/Mad-Pascal#38]
I have a suggestion for a new modifier for procedures/functions. MACRO.

Its purpose would be to insert the whole code of the procedure/function at the place of procedure or function call.
The idea is to force the compiler not to use the JMP/JSR instruction.

In case of designing fast recursive calls, it would cost the code size, but (I hope) it would speed up the code execution, e.g. in loops.

**Comment by zbyti** [comment]
You mean **inline** functions? Macros in Pascal are https://github.com/tebe6502/Mad-Pascal/issues/41

**Comment by GSoftwareDevelopment** [comment]
Yes, that's exactly what I mean. :)

**Comment by GSoftwareDevelopment** [comment]
Why don't I have insight into other Issues as just mine?

**Comment by GSoftwareDevelopment** [comment]
Moving on, I ask the question:

**Why don't I see all the reported cases?**

This makes me misinformed and aware of global reported bugs/innovations.

(Sorry to post this in this thread, but this is the one that showed I can't see everything that is going on)

**Comment by zbyti** [comment]
If you become **Mad Pascal Contributor** then you'll see all reported cases :]

**Comment by GSoftwareDevelopment** [comment]
Sorry, but I don't know everything in GitHubs yet - thanks for explaining

**Comment by zbyti** [comment]
https://github.com/tebe6502/Mad-Pascal/commit/fc7ae03baafc176af3d153bccd979ee5ed4dbdfd :]

**Comment by GSoftwareDevelopment** [comment]
Woow. So `inline` works like this :) OK, there was no topic :D
