### ISSUE TITLE
current master unhandled exception

### ISSUE THREAD

**Issue by zbyti** [tebe6502/Mad-Pascal#4]
mp-build sieve.pas 
Mad Pascal Compiler version 1.6.4 [2020/05/03] for 6502
Compiling sieve.pas
An unhandled exception occurred at $000000000044444F:
EAccessViolation: Access violation
  $000000000044444F

ZPAGE: $0080..$00DA
RTLIB: $2000..$2058
; -------------
sieve.a65 (471) ERROR: Missing .ENDL
	STATICDATA
sieve.a65 (90) ERROR: Undeclared macro STATICDATA (BANK=0)
	stx MAIN.@halt+1
sieve.a65 (105) ERROR: Undeclared label MAIN.@HALT (BANK=0)
VLEN	= VARDATASIZE-VARINITSIZE
sieve.a65 (111) ERROR: Undeclared label VARDATASIZE (BANK=0)
VADR	= DATAORIGIN+VARINITSIZE
sieve.a65 (112) ERROR: Undeclared label DATAORIGIN (BANK=0)
	ift VADR > $BFFF
sieve.a65 (114) ERROR: The referenced label VADR has not previously been defined properly
	eli (VLEN>0) && (VLEN<=256)
sieve.a65 (116) ERROR: The referenced label VLEN has not previously been defined properly
	eli VLEN>0
sieve.a65 (120) ERROR: The referenced label VLEN has not previously been defined properly
	mwa #PROGRAMSTACK psptr
sieve.a65 (124) ERROR: Undeclared label PROGRAMSTACK (BANK=0)
 mva $340,x MAIN.IOCB@COPY,x-
sieve.a65 (127) ERROR: Undeclared label MAIN.IOCB@COPY (BANK=0)
	UNITINITIALIZATION
sieve.a65 (138) ERROR: Undeclared macro UNITINITIALIZATION (BANK=0)
	jmp l_0034
sieve.a65 (142) ERROR: Undeclared label L_0034 (BANK=0)
SCREENWIDTH	= DATAORIGIN+$0000
sieve.a65 (243) ERROR: Undeclared label DATAORIGIN (BANK=0)
SCREENHEIGHT	= DATAORIGIN+$0002
sieve.a65 (244) ERROR: Undeclared label DATAORIGIN (BANK=0)
DATESEPARATOR	= DATAORIGIN+$0004
sieve.a65 (245) ERROR: Undeclared label DATAORIGIN (BANK=0)
FILEMODE	= DATAORIGIN+$0005
sieve.a65 (251) ERROR: Undeclared label DATAORIGIN (BANK=0)
GRAPHMODE	= DATAORIGIN+$0006
sieve.a65 (252) ERROR: Undeclared label DATAORIGIN (BANK=0)
IORESULT	= DATAORIGIN+$0007
sieve.a65 (253) ERROR: Undeclared label DATAORIGIN (BANK=0)
EOLN	= DATAORIGIN+$0008
sieve.a65 (254) ERROR: Undeclared label DATAORIGIN (BANK=0)
RNDSEED	= DATAORIGIN+$0009
sieve.a65 (255) ERROR: Undeclared label DATAORIGIN (BANK=0)
	sta Result
sieve.a65 (367) ERROR: The referenced label RESULT has not previously been defined properly
	mva RESULT :STACKORIGIN,x
sieve.a65 (379) ERROR: The referenced label RESULT has not previously been defined properly
RESULT	= DATAORIGIN+$000C
sieve.a65 (391) ERROR: Undeclared label DATAORIGIN (BANK=0)
@VarData	= RESULT
sieve.a65 (393) ERROR: The referenced label RESULT has not previously been defined properly
TEXTATTR	= DATAORIGIN+$000B
sieve.a65 (401) ERROR: Undeclared label DATAORIGIN (BANK=0)
	mva :rtclok+2 Result
sieve.a65 (464) ERROR: Undeclared label RESULT (BANK=0)
	mva :rtclok+1 Result+1
sieve.a65 (465) ERROR: Undeclared label RESULT (BANK=0)
	mva :rtclok Result+2
sieve.a65 (466) ERROR: Undeclared label RESULT (BANK=0)
	mva #$00 Result+3
sieve.a65 (467) ERROR: Undeclared label RESULT (BANK=0)
Writing listing file...

[sieve.txt](https://github.com/tebe6502/Mad-Pascal/files/4570305/sieve.txt)

**Comment by tebe6502** [comment]
fixed

**Comment by zbyti** [comment]
confirm, thx :]
