### ISSUE TITLE
Feature Request: output flag

### ISSUE THREAD

**Issue by zbyti** [tebe6502/Mad-Pascal#64]
MADS ma flagę `-o` która pozwala wskazać miejsce docelowe dla pliku binarnego.

Mad Pascal też ma flagę `-o` ale oznacza ona optymalizację.

Potrzebował bym w Mad Pascalu również możliwości wskazania docelowego miejsca dla np. `foo.a65`. Najlepiej jakby te flagi uzyskały spójność znaczeniową i `-o` w MP przerodziło się np. `-opt` a `-o` zaczęło oznaczać `output`.

**Comment by zbyti** [comment]
zwłaszcza, że ja słyszę `-o` i tak nic nie robi ;)

**Comment by tebe6502** [comment]
dodany przełącznik -o:filename [-o filename]

**Comment by zbyti** [comment]
THX!
