### ISSUE TITLE
Feature Request: Lazarus *.lpr project

### ISSUE THREAD

**Issue by zbyti** [tebe6502/Mad-Pascal#65]
```
mp main.lpr 
Mad Pascal Compiler version 1.6.6 [2021/11/02] for 6502
Error: Can't open file 'main.pas'
```
Wygodnie by było jakby Mad Pascal nie narzekał na rozszerzenie używane przez Lazarus IDE.

**Comment by tebe6502** [comment]
obecnie kompilator nie zmienia już rozszerzenia kompilowanego pliku na *.pas

**Comment by zbyti** [comment]
THX!
