### ISSUE TITLE
If the "-target: raw" compiler switch is used, the "-code:" directive is ignored. 

### ISSUE THREAD

**Issue by pvawatson** [tebe6502/Mad-Pascal#72]
If the "-target: raw" compiler switch is used, the "-code:" directive is ignored. The fixed address $1000 is used to start the program instead of the one specified in the "-code:" switch.

**Comment by tebe6502** [comment]
fixed

**Comment by pvawatson** [comment]
Works, but it is desirable that the code starts from the address specified in "-code", and not 3 bytes earlier.

**Comment by tebe6502** [comment]
fixed
