### ISSUE TITLE
Resources and relationships between resources ( attention: long text)

### ISSUE THREAD

**Issue by GSoftwareDevelopment** [tebe6502/Mad-Pascal#74]
# Mój problem

Mam taką sytuację z plikiem zasobów `recource.rc`
~~~
SFX_DATA_ADDR rcasm 'data.asm';
SFX_ORG rcasm 'mole.asm';
~~~

Pierwszy z nich `data.asm` zawiera definicje danych wraz z przypisanymi doń odpowiednimi etykietami, np:
(fragment pliku data.asm)
~~~
data_sfx_0 ; KEY CLEAN LONG
	.by $7C $A6 $00 $A5 $00 $A4 $01 $A3 $00 $A3 $00 $A3 $3F $A3 $00 $A3 
	.by $00 $A3 $83 $00 

; address: $C014 (offset: $0014)
data_sfx_1 ; KEY CLEAN ECHO
	.by $7C $A6 $00 $A5 $00 $A4 $00 $A3 $00 $A2 $00 $A1 $80 $00 
~~~

Drugi `mole.asm`, też zawiera definicje danych, ale korzysta z etykiet z pierwszego pliku.
(fragment pliku mole.asm)
~~~
;	org $7126	; ----------------------------------------

; current block address: 7126

sfxptr
	dta a(data_sfx_0) ; offset in data 0000 optimized 1=>0
	dta a(data_sfx_1) ; offset in data 0014 optimized 2=>1
~~~

Jak sprawić, by taka sytuacja zadziałała? Czy to jest w ogóle możliwe, by w jednym pliku zasobów wykorzystać etykiety z drugiego pliku? Jeśli jest to wykonalne, to byłbym ogromnie wdzięczny za, wytłumaczenie, jak należy się odwołać w drugim pliku do etykiet z pierwszego. Dziękuję

---

Z tego co widzę w pliku `A65` (po kompilacji MP) jest w nim taka klauzula:
~~~
.local	RESOURCE
	icl 'atari\resource.asm'
	?EXTDETECT = 0
	?VBXDETECT = 0

	RCASM 'song/data.asm' SFX_API.SFX_DATA_ADDR 0 0 0 0 0 0 0 0
	RCASM 'song/mole.asm' SFX_API.SFX_ORG 0 0 0 0 0 0 0 0
.endl
~~~

Rozumiem, że zasoby `RCASM` będą kompilowane w przestrzeni nazw `RESOURCE`.
Czy poszczególne zasoby (linie `RCASM`) dostają jeszcze jakąś własną przestrzeń nazw?

**Comment by GSoftwareDevelopment** [comment]
# Moje rozwiązanie

Zacznę może od tego, jak odpowiedź znalazłem.
Podczas kompilacji pliku **A65** przez MADSA, może on generować listę wszystkich etykiet, jakie są wykorzystane w pliku źródłowym **A65**.
Właśnie tam udało mi się znaleźć odwołania do etykiet z pliku zasobu `data.asm`. Wygląda to tak:

~~~
...
00	209E	RESOURCE.RESOURCE.RCASM12.RESOURCE.DATA
00	C000	RESOURCE.RESOURCE.RCASM12.RESOURCE._SFX_API.SFX_DATA_ADDR
00	C000	RESOURCE.RESOURCE.RCASM12.RESOURCE._SFX_API.SFX_DATA_ADDR.DATA
00	C000	RESOURCE.RESOURCE.RCASM12.RESOURCE._SFX_API.SFX_DATA_ADDR.DATA_SFX_0
00	C014	RESOURCE.RESOURCE.RCASM12.RESOURCE._SFX_API.SFX_DATA_ADDR.DATA_SFX_1
...
~~~

Wprowadziłem te etykiety do pliku `mole.asm`:

~~~
sfxptr
	dta a(RESOURCE.RESOURCE.RCASM12.RESOURCE._SFX_API.SFX_DATA_ADDR.data_sfx_0) ; offset in data 0000 optimized 1=>0
	dta a(RESOURCE.RESOURCE.RCASM12.RESOURCE._SFX_API.SFX_DATA_ADDR.data_sfx_1) ; offset in data 0014 optimized 2=>1
~~~

I to pozwoliło, skompilować kod do końca i prawidłowo.

# Co mnie w tym gryzie?

Uzależnienie od czynników kompilacji źródeł MP.

Zakładam, że, jeżeli zmieniona zostanie kolejność "wywołania" zasobów, zmieni się również liczba porządkowa dla `RESOURCE.RESOURCE.RCASMxx`. Więc nie można "ufac" takiemu rozwiązaniu problemu.

Poza tym. Ścieżka przestrzeni nazw do zasobu jest niesamowicie długa w dodatku przekombinowana.

**Comment by GSoftwareDevelopment** [comment]
# Jak bym to widział ja.

Skoro i tak, każdy zasób `rcasm` ma dedykowaną przestrzeń nazw, tj. w powyższym przypadku jest to `_SFX_API.SFX_DATA_ADDR` to po co numerować `RCASMxx`.
Ok. Zauważyłem, że dla każdego `RCASMxx` deklarowana są jeszcze dodatkowe etykiety:

~~~
RCASM12.RESOURCE.LEN
RCASM12.RESOURCE.MCPY
RCASM12.RESOURCE.DATA
~~~

Nie dałoby się tego jakoś związać z etykietą `_SFX_API.SFX_DATA_ADDR`, i ogólnie uprościć ścieżkę? Np:

~~~
RESOURCE.RCASM._SFX_API.SFX_DATA_ADDR_LEN
RESOURCE.RCASM._SFX_API.SFX_DATA_ADDR_MCPY
RESOURCE.RCASM._SFX_API.SFX_DATA_ADDR_DATA
~~~

Serio. To wygląda znacznie lepiej i jest bardziej intuicyjne dla programisty.
Nawet w trakcie debugowania (pod Altirrą), będzie wygodniejsze, bo krótsze i czytelniejsze.

**Comment by zbyti** [comment]
Drogi użytkowniku.

W imieniu autora i kontrybutorów projektu pragniemy Cię poinformować, że przyjrzeliśmy się zgłoszeniu i jesteśmy na etapie dyskusji nad możliwości zrealizowania Twojej propozycji.

Niestety w naszej grupie nie zapadł jeszcze konsensus w tej sprawie.

@tebe6502 jako główny programista jest oczywiście bardzo chętny popracować nad tym, niestety jest przeze mnie powstrzymywany bo mam pewne zastrzeżenia.

Niestety to nie miejsce na upublicznianie naszych wewnętrznych przepychanek.

Jeżeli chciałbyś przekonać nas do swojego rozwiązania to proponuję do zgłoszenia dołączyć PR z kodem, wtedy nasza dyskusja nad rozwiązaniem problemu może się uprościć od strony technicznej.

z wyrazami szacunku
Bartek

**Comment by tebe6502** [comment]
.def :label
tworzy etykietę w głównej przestrzeni nazw, dzięki czemu będzie widziana z każdego miejsca

.def :data_sfx_0 ; KEY CLEAN LONG

	.by $7C $A6 $00 $A5 $00 $A4 $01 $A3 $00 $A3 $00 $A3 $3F $A3 $00 $A3 
	.by $00 $A3 $83 $00 

; address: $C014 (offset: $0014)
.def :data_sfx_1 ; KEY CLEAN ECHO
	.by $7C $A6 $00 $A5 $00 $A4 $00 $A3 $00 $A2 $00 $A1 $80 $00

**Comment by tebe6502** [comment]
http://mads.atari8.info/pl/skladnia/

rodział: Globalne

**Comment by GSoftwareDevelopment** [comment]
@tebe - to zła praktyka, by biblioteka lokowała etykiety w głównej przestrzeni nazw. Ma od tego lokalna przestrzeń, by tam były i z niej korzystać.

@zbyti Nie wiem co to jest PR z kodem 🥺

**Comment by GSoftwareDevelopment** [comment]
wszystko o czym pisze  nie jest przymusem. To propozycje, które wcale nie muszą być jakkolwiek rozpatrzane - ja się dostosuje, najwyżej... zwalę trochę obowiązków na użytkownika końcowego. 😉

**Comment by zbyti** [comment]
@GSoftwareDevelopment https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by tebe6502** [comment]
każdy typ zasobu ma dedykowane makro, które jest wywoływane, w przypadku RCASM (plik BASE\ATARI\RESOURCE.ASM)

/* ----------------------------------------------------------------------- */
/* RCASM
/* ----------------------------------------------------------------------- */

.macro	RCASM (nam, lab)

	org RESORIGIN

len = .sizeof(_%%2)

mcpy	ift main.%%lab+len >= $bc20
	mva #0 sdmctl
	sta dmactl
	eif

	jsr sys.off

	memcpy #data #main.%%lab #len

	jmp sys.on
data

.local	_%%2, main.%%lab

	icl %%1

.endl
	.print '$R RCASM   ',main.%%lab,'..',main.%%lab+len-1," %%1"

	ini mcpy
.endm

**Comment by GSoftwareDevelopment** [comment]
@zbyti Dzięki za możliwość (samodzielnego) rozwoju projektu, ale nie skorzystam. Powód jest prosty: _Nie mam czasu "studiować" kodu kompilatora i zasad jego działania_. I może na tym poprzestanę, gdyż (jak to napisałeś) _"...to nie miejsce na upublicznianie naszych wewnętrznych przepychanek."_ - na szczęście.
Nie mam zamiaru psuć dobrego imienia Waszego, ani Projektu.

Pozrawiam i... zamykam wątek.
