### ISSUE TITLE
Pointer arithmetic not compatible with FPC

### ISSUE THREAD

**Issue by SignumTemporis** [tebe6502/Mad-Pascal#75]
## Issue description

Adding to a pointer doesn't work in Mad-Pascal while it does in FPC.

## Code to reproduce the issue
```Pascal
uses crt;

var
  a: array [0..1] of Byte = (2, 3);
  p: ^Byte = @a;

begin
  WriteLn(Word(@a));
  WriteLn(Word(@a[0]));
  WriteLn(a[0], ' ', a[1]);
  WriteLn;
  WriteLn(Word(p));
  WriteLn(Word(Pointer(p)));
  WriteLn(Byte((Pointer(p)+0)^), ' ', Byte((Pointer(p)+1)^));    // (1)

  ReadKey();
end.
```

## FPC -MDelphi

OS: Ubuntu 20.04.3 x86_64
FPC 3.2.2

Output:
```
59424
59424
2 3

59424
59424
2 3
```

## Mad-Pascal

Mad-Pascal Compiler version cca6b6f3a3b3e1c0e96f20c24ca29c2fc05faa99

Output:
```
Compiling ./test1.pas
./test1.pas (14,27) Error: Incompatible types: got "BYTE" expected "POINTER"
```

**Comment by tebe6502** [comment]
issue #75 fixed, https://github.com/tebe6502/Mad-Pascal/blob/master/samples/tests/tests-pointer/arithmetic.pas

**Comment by SignumTemporis** [comment]
Works for me after the fix.
