### ISSUE TITLE
Unable to initialize a record pointer in declaration

### ISSUE THREAD

**Issue by SignumTemporis** [tebe6502/Mad-Pascal#76]
## Issue description

An initialized variable of a pointer to a record (like `(1)` in the code below) has value `0` regardless of actual initial value.

## Code to reproduce the issue
```Pascal
uses crt;

type
  TRecord = record x, y: Byte end;

var
  a: array [0..1] of Byte = (2, 3);
  p: ^TRecord = @a;   // (1)

begin
  // p := @a;   // (2)

  WriteLn(Word(@a));
  WriteLn(a[0], ' ', a[1]);
  WriteLn;
  WriteLn(Word(p));
  WriteLn(p^.x, ' ', p^.y);

  ReadKey();
end.
```

`(1)` - initialized pointer variable which doesn't work
`(2)` - a workaround

## FPC -MDelphi

OS: Ubuntu 20.04.3 x86_64
FPC 3.2.2

Output for both cases of `(2)`:
```
59424
2 3

59424
2 3
```

## Mad-Pascal

Mad-Pascal Compiler version cca6b6f3a3b3e1c0e96f20c24ca29c2fc05faa99

Output when `(2)` commented:
```
8597
2 3

0
0 0
```

Output when `(2)` uncommented:
```
8597
2 3

8597
2 3
```

**Comment by SignumTemporis** [comment]
Code simplified for testing:
```pascal
uses crt;

type
  TRecord = record x, y: Byte end;

var
  a: array [0..1] of Byte = (2, 3);
  p: ^TRecord = @a;

begin
  WriteLn((p <> Nil) and (p = @a));

  repeat until KeyPressed();
end.
```

Expected result:
```
TRUE
```

**Comment by tebe6502** [comment]
fixed, https://github.com/tebe6502/Mad-Pascal/blob/master/samples/tests/tests-record/record_initialize.pas

**Comment by SignumTemporis** [comment]
It works for me after the fix.
