### ISSUE TITLE
Unable to use fields from a record pointer passed to a procedure

### ISSUE THREAD

**Issue by SignumTemporis** [tebe6502/Mad-Pascal#78]
## Issue description

The use of fields of a record dereferrenced from a pointer passed to a procedure cause the code to compile but the MADS is not able to produce a binary.

## Code to reproduce the issue
```Pascal
uses crt;

type
  TRecord = record x, y: Byte end;
  TRecordPtr = ^TRecord;

var
  r: TRecord;
  p: ^TRecord;

procedure PrintRecord(p1: TRecordPtr);
begin
  WriteLn(p1^.x, ' ', p1^.y);
end;

begin
  r.x := 2;
  r.y := 3;
  p := @r;

  WriteLn(Word(@r));
  PrintRecord(@r);
  WriteLn;
  WriteLn(Word(p));
  PrintRecord(p);

  ReadKey();
end.
```

## FPC -MDelphi

OS: Ubuntu 20.04.3 x86_64
FPC 3.2.2

Output:
```
44880
2 3

44880
2 3
```

## Mad-Pascal

Mad-Pascal Compiler version cca6b6f3a3b3e1c0e96f20c24ca29c2fc05faa99
Mad-Assembler version ecb0c7e11b61a1fc4d36d10a9fb21ef83280cf02

Output:
```
 mva (:bp2),y adr.P1,y-
test4.a65 (421) ERROR: Undeclared label ADR.P1 (BANK=0)
        mwa #adr.P1 P1
test4.a65 (422) ERROR: Undeclared label ADR.P1 (BANK=0)
```

**Comment by SignumTemporis** [comment]
Code simplified for testing:
```pascal
uses crt;

type
  TRecord = record x, y: Byte end;
  TRecordPtr = ^TRecord;

var
  r: TRecord;
  p: ^TRecord;

procedure PrintProduct(p1: TRecordPtr);
begin
  WriteLn(p1^.x * p1^.y);
end;

begin
  r.x := 2;
  r.y := 3;
  p := @r;

  PrintProduct(p);

  ReadKey();
end.
```

Expected result:
```
6
```

**Comment by tebe6502** [comment]
issue #78 fixed, https://github.com/tebe6502/Mad-Pascal/blob/master/samples/tests/tests-record/record_dereference_as_val.pas

**Comment by SignumTemporis** [comment]
Works for me after the fix.
