### ISSUE TITLE
Writing a value to a two-dimensional Float16 array does not work correctly

### ISSUE THREAD

**Issue by SignumTemporis** [tebe6502/Mad-Pascal#85]
## Issue description

Writing a value to a two-dimensional Float16 array does not work correctly.
When You use Single or Byte instead of Float16 in the same code then it produces expected results.

Mad-Pascal Compiler version 3bd174c4e93dac256d25307c2afcb3100d5a8307
Mad-Assembler version 40bfd8045e7ae28174c5f074ea7f96d59fd1f248

## Code to reproduce the issue
```Pascal
uses crt;

var
  t: array [0..1, 0..2] of Float16;

procedure Add(x, y: Float16);
  var k: SmallInt = 0;
begin
  t[k,0] := x;
  t[k,1] := y;
  t[k,2] := t[k,0] + t[k,1];
end;

procedure Print;
begin
  WriteLn(t[0,0], ' ', t[0,1], ' ', t[0,2]);
end;

begin
  Add(1, 2);
  Print;

  ReadKey();
end.
```

### Expected
```
1.000000 2.000000 3.000000
```
### Actual
```
1.000000 2.001953 0.000000
```

**Comment by tebe6502** [comment]
issue #85 fixed

function 'CardToHalf' has been improved

  if frac(s) <> 0 then

   Result := f32Tof16(Src)

  else begin

**Comment by SignumTemporis** [comment]
The sample above works now.

However there is still some issue.
When I try the following code then I get wrong results again:

```Pascal
uses crt;

var
  t: array [0..1, 0..3] of Float16;

procedure Add(x, y, s: Float16);
var k: Byte = 0;
begin
  t[k,0] := x + s;
  t[k,1] := y + s;
  t[k,2] := t[k,0];
  t[k,3] := t[k,1];
end;

procedure Print;
var j: Byte;
begin
  for j := 0 to 3 do begin
    WriteLn(j, ' ', t[0,j]);
  end;
end;

begin
  Add(10, 20, 5);
  Print;

  ReadKey();
end.
```

Expected output:
```
0 15.000000
1 25.000000
2 15.000000
3 25.000000
```
Actual output:
```
0 15.000000
1 0.000000
2 15.000000
3 0.000000
```

What's interesting when I remove `var k` declaration from `Add` and replace index `k` with `0` then I get expected result.

**Comment by tebe6502** [comment]
The float16 library uses the variable EAX just like the multiplication routine. Two-dimensional arrays use multiplication. Yes, this needs to be corrected.

**Comment by tebe6502** [comment]
fixed

**Comment by SignumTemporis** [comment]
Works for me now.
